steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_IMAGE}', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_IMAGE}']
substitutions:
  _IMAGE: '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/ux-copy-sync:$SHORT_SHA'
  _REGION: asia-southeast1
  _REPOSITORY: ux-copy-sync-images
images: ['${_IMAGE}']
